Repository HopeGaarden/BlueRose, pull requests merged in 2024-03, with the labels that each got.

#2 chore: 프로젝트 세팅
  .github/issue_template.md
  .github/pull_request_template.md
  Back/.gitignore
  Back/build.gradle
  Back/gradle/wrapper/gradle-wrapper.jar
  Back/gradle/wrapper/gradle-wrapper.properties
  Back/gradlew
  Back/gradlew.bat
  Back/settings.gradle
  Back/src/main/java/com/example/back/BackApplication.java
  Back/src/main/resources/application.properties
  Back/src/test/java/com/example/back/BackApplicationTests.java
Labels: chore, 이주성

#5 chore: 설정 파일 암호화 - jasypt 적용
  Back/build.gradle
  Back/src/main/java/com/example/back/config/JasyptConfig.java
  Back/src/main/resources/application-local.yml
  Back/src/main/resources/application-test.yml
  Back/src/main/resources/application.properties
  Back/src/main/resources/application.yml
  Back/src/test/java/com/example/back/BackApplicationTests.java
  Back/src/test/java/com/example/back/config/IntegrationHelper.java
  Back/src/test/java/com/example/back/config/JasyptConfigTest.java
Labels: chore, 이주성

#7 chore(#6): querydsl 설정
  Back/.gitignore
  Back/build.gradle
  Back/src/main/java/com/example/back/config/QueryDslConfig.java
Labels: chore, 이주성

#9 chore(#8): README 작성
  README.md
Labels: chore, 이주성

#11 chore(#10): README 수정(정원 프로필)
  README.md
Labels: chore, 이정원

#16 Refactor(#13): yml 파일 관리 방법 변경
  Back/.gitignore
  Back/build.gradle
  Back/src/main/java/com/example/back/config/JasyptConfig.java
  Back/src/main/resources/application-local.yml
  Back/src/main/resources/application-test.yml
  Back/src/main/resources/application.yml
  Back/src/test/java/com/example/back/config/JasyptConfigTest.java
Labels: refactor, 이주성

#18 Feat(#17): baseentity 및 member 엔티티 생성
  Back/src/main/java/com/example/back/BackApplication.java
  Back/src/main/java/com/example/back/domain/BaseEntity.java
  Back/src/main/java/com/example/back/domain/auth/member/Member.java
  Back/src/main/java/com/example/back/domain/auth/member/constant/MemberRole.java
  Back/src/main/java/com/example/back/domain/auth/member/repository/MemberRepository.java
  Back/src/test/java/com/example/back/BackApplicationTests.java
Labels: feat, 이주성

#22 chore(#21): cors 설정 및 security 세팅
  Back/src/main/java/com/example/back/api/test/TestController.java
  Back/src/main/java/com/example/back/config/AuthConfig.java
  Back/src/main/java/com/example/back/config/SecurityConfig.java
  Back/src/main/java/com/example/back/config/WebMvcConfig.java
  Back/src/main/java/com/example/back/domain/auth/member/Member.java
  Back/src/test/java/com/example/back/config/SecurityConfigTest.java
Labels: chore, 이주성

#35 feat(#23): 로그인 & 로그아웃 로직 구현
  Back/build.gradle
  Back/src/main/java/com/example/back/api/auth/controller/AuthController.java
  Back/src/main/java/com/example/back/api/auth/controller/request/AuthRequest.java
  Back/src/main/java/com/example/back/api/auth/controller/response/LoginResponse.java
  Back/src/main/java/com/example/back/api/auth/service/AuthService.java
  Back/src/main/java/com/example/back/api/auth/service/LogoutService.java
  Back/src/main/java/com/example/back/api/auth/service/jwt/JwtTokenProvider.java
  Back/src/main/java/com/example/back/api/auth/service/response/AuthResponse.java
  Back/src/main/java/com/example/back/common/exception/ExceptionMessage.java
  Back/src/main/java/com/example/back/common/utils/TokenUtil.java
  Back/src/main/java/com/example/back/common/validation/EmailValidator.java
  Back/src/main/java/com/example/back/common/validation/IsEmail.java
  Back/src/main/java/com/example/back/config/AuthConfig.java
  Back/src/main/java/com/example/back/config/redis/RedisConfig.java
  Back/src/main/java/com/example/back/config/security/SecurityConfig.java
  Back/src/main/java/com/example/back/config/security/filter/JwtAuthenticationFilter.java
  Back/src/main/java/com/example/back/domain/auth/member/Member.java
  Back/src/main/java/com/example/back/domain/auth/member/constant/MemberRole.java
  Back/src/main/java/com/example/back/domain/token/jwt/JwtToken.java
  Back/src/main/java/com/example/back/domain/token/jwt/repository/JwtTokenRepository.java
  Back/src/main/java/com/example/back/domain/token/jwt/repository/TokenRepository.java
  Back/src/main/java/com/example/back/domain/token/refresh/RefreshToken.java
  Back/src/main/java/com/example/back/domain/token/refresh/repository/RefreshTokenRepository.java
  Back/src/test/java/com/example/back/api/auth/controller/AuthControllerTest.java
  Back/src/test/java/com/example/back/api/auth/service/AuthServiceTest.java
  Back/src/test/java/com/example/back/api/auth/service/jwt/JwtTokenProviderTest.java
  Back/src/test/java/com/example/back/config/SecurityConfigTest.java
  Back/src/test/java/com/example/back/domain/auth/MemberFixture.java
  Back/src/test/java/com/example/back/domain/token/jwt/repository/JwtTokenRepositoryTest.java
  Back/src/test/java/com/example/back/domain/token/refresh/repository/RefreshTokenRepositoryTest.java
Labels: feat, 이주성
