Repository HopeGaarden/BlueRose, pull requests merged in 2024-05, with the labels that each got.

#53 feat: 북마크 기능 구현
  Back/src/main/java/com/example/back/api/auth/service/MemberService.java
  Back/src/main/java/com/example/back/api/feed/controller/BookmarkController.java
  Back/src/main/java/com/example/back/api/feed/controller/FeedInfoController.java
  Back/src/main/java/com/example/back/api/feed/service/BookmarkService.java
  Back/src/main/java/com/example/back/api/feed/service/FeedInfoService.java
  Back/src/main/java/com/example/back/domain/feed/bookmark/repository/BookmarkRepository.java
  Back/src/main/java/com/example/back/domain/feed/feedinfo/repository/FeedInfoRepository.java
  Back/src/main/java/com/example/back/domain/feed/tag/TagInfo.java
  Back/src/main/java/com/example/back/domain/feed/tag/repository/TagInfoRepository.java
  Back/src/main/java/com/example/back/global/exception/BookmarkException.java
  Back/src/main/java/com/example/back/global/exception/ExceptionMessage.java
Labels: feat, 소경민

#54 feat(#48): 질병백과 나무위키 기능 구현
  Back/build.gradle
  Back/src/main/java/com/example/back/api/auth/service/AuthService.java
  Back/src/main/java/com/example/back/api/disease/service/DiseaseMemberService.java
  Back/src/main/java/com/example/back/api/wiki/controller/DiseaseWikiController.java
  Back/src/main/java/com/example/back/api/wiki/controller/request/DiseaseWikiPatchRequest.java
  Back/src/main/java/com/example/back/api/wiki/controller/request/DiseaseWikiSaveRequest.java
  Back/src/main/java/com/example/back/api/wiki/service/DiseaseWikiService.java
  Back/src/main/java/com/example/back/api/wiki/service/response/DiseaseWikiResponse.java
  Back/src/main/java/com/example/back/api/wiki/service/response/WikiResolveConflictResponse.java
  Back/src/main/java/com/example/back/common/utils/DiffDTO.java
  Back/src/main/java/com/example/back/common/utils/DiffService.java
  Back/src/main/java/com/example/back/domain/auth/disease/DiseaseInfo.java
  Back/src/main/java/com/example/back/domain/auth/disease/DiseaseMember.java
  Back/src/main/java/com/example/back/domain/auth/disease/DiseaseMemberStatus.java
  Back/src/main/java/com/example/back/domain/auth/disease/repository/DiseaseInfoRepository.java
  Back/src/main/java/com/example/back/domain/auth/disease/repository/DiseaseMemberRepository.java
  Back/src/main/java/com/example/back/domain/auth/medical/DiseaseInfo.java
  Back/src/main/java/com/example/back/domain/auth/medical/MedicalInfo.java
  Back/src/main/java/com/example/back/domain/auth/member/Member.java
  Back/src/main/java/com/example/back/domain/group/groupInfo/GroupInfo.java
  Back/src/main/java/com/example/back/domain/group/groupInfo/GroupStatus.java
  Back/src/main/java/com/example/back/domain/wiki/DiseaseWiki.java
  Back/src/main/java/com/example/back/domain/wiki/repository/DiseaseWikiRepository.java
  Back/src/main/java/com/example/back/global/exception/DiseaseInfoException.java
  Back/src/main/java/com/example/back/global/exception/DiseaseMemberException.java
  Back/src/main/java/com/example/back/global/exception/DiseaseWikiException.java
  Back/src/main/java/com/example/back/global/exception/ExceptionMessage.java
  Back/src/main/java/com/example/back/global/exception/handler/GlobalExceptionHandler.java
  Back/src/test/java/com/example/back/api/disease/service/DiseaseMemberServiceTest.java
  Back/src/test/java/com/example/back/api/wiki/service/DiseaseWikiServiceMockTest.java
  Back/src/test/java/com/example/back/api/wiki/service/DiseaseWikiServiceTest.java
  Back/src/test/java/com/example/back/config/IntegrationHelper.java
  Back/src/test/java/com/example/back/domain/auth/MemberFixture.java
Labels: feat, 이주성

#62 refactor(#61): 진단서 질병명 추출 추가
  Back/src/main/java/com/example/back/api/auth/service/AuthService.java
  Back/src/main/java/com/example/back/api/auth/service/OCRService.java
  Back/src/main/java/com/example/back/domain/auth/medical/MedicalInfo.java
Labels: refactor, 소경민

#64 feat(#63): 회원가입시 질병 그룹화 구현
  Back/src/main/java/com/example/back/api/auth/service/AuthService.java
  Back/src/main/java/com/example/back/domain/auth/disease/DiseaseInfo.java
  Back/src/main/java/com/example/back/domain/auth/disease/repository/DiseaseInfoRepository.java
Labels: feat, 소경민
